# Generated by Django 4.1.1 on 2022-09-16 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app556', '0002_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='discription',
            new_name='description',
        ),
    ]
